### ISSUE TITLE
Ember Octane todo list

### ISSUE THREAD

**Issue by lifeart** [JennyJudova/ember-to-do-list#1]
Good job! 

I see little bit outdated syntax, check out https://github.com/NullVoxPopuli/ember-todomvc-tutorial and https://ember-learn.github.io/ember-octane-vs-classic-cheat-sheet/ to get latest most exiting ember DX!

**Comment by JennyJudova** [comment]
Yes, I started following teh tutorial and 15 min in realised its 5 years old 😆 So scrapped this looking into octane now so thanks for sharing the cheat sheet :)

**Comment by lifeart** [comment]
Yeah, alot of Ember documentation pretty outdated. 
Upstream links: 

Community documentation - https://www.notion.so/Editors-Tooling-5da96f0b2baf4ce1bf3fd58e3b60c7f6 
Official guides - https://guides.emberjs.com/release/ 
Community discord - https://discordapp.com/channels/480462759797063690

Hope it can help you check Ember Octane Power! :)
